### ISSUE TITLE
Is Hyper_ `logs` command work differently from docker? 

### ISSUE THREAD

**Issue by Crazykev** [hyperhq/hypercli#14]
Now, `hyper logs` could only get a running container's logs, which is different from docker. Is that normal or just  a bug not been fixed yet?
Similar to this, 
* If we get logs from a stopped container, there will be an error.
* If we restart a container, logs from the previous running will no longer be exist.

**Comment by carmark** [comment]
yeah, it is a known issue, will fix it later.
