### ISSUE TITLE
[bug] Command `kill` does not work properly

### ISSUE THREAD

**Issue by Crazykev** [hyperhq/hypercli#15]
1. When kill a running container, get error message "Error response from daemon: Cannot kill container X: Container X is not running".
    How to Reproduce:  
    `hyper run -d busybox top`
    `hyper kill $contianer_id`

2. When kill a stoped container, we should get an error message, something like we got from [1]. While we only got a container id.

**Comment by carmark** [comment]
retry this test case again please.

**Comment by Crazykev** [comment]
Test case passed, close this.
