### ISSUE TITLE
Auto update version crashes in Windows

### ISSUE THREAD

**Issue by phrozen** [hyperhq/hypercli#163]
I downloaded the version on the webpage and it runs fine the first time, but after running a single 'hyper' command at the end of the command options it says 'Found a newer version, downloading...'

It overwrites the binary and this new version does not work on Windows 10 Pro x64, it says its a 16 bit app and that it is not compatible with my corrent OS.

**Comment by carmark** [comment]
Hello @phrozen 

Thanks for reporting this issue, I built it on Windows 7, and it works well.  Could you please send out the crash stack?

Thanks,

**Comment by phrozen** [comment]
There is no crash stack as the application won't even start. I hope the image makes it clear, after an auto update with command 'hyper', the new binary is not compatible.

![hyper error](https://cloud.githubusercontent.com/assets/213238/18653549/3f9d47fc-7ea0-11e6-87fb-4e62bb2b1c21.jpg)

**Comment by carmark** [comment]
hello @phrozen 

Could you please download [it](https://hyper-install.s3.amazonaws.com/hyper-win64.zip) and try it again?  We have fixed a configured issue.

Thanks,

**Comment by phrozen** [comment]
Done, it no longer auto updates into a faulty binary. Thank you!
