### ISSUE TITLE
Compose up errors with "This project already exists."

### ISSUE THREAD

**Issue by passcod** [hyperhq/hypercli#176]
When running `compose up`, the first time the services are started fine. If I then try to run `compose up` again, whether the docker-compose.yml has changed or not, it always answers with "This project already exists."

What I expect: that `compose up` updates the services.

How to reproduce:
1. Create docker-compose.yml file with a service definition.
2. Run `hyper compose up` and wait until services start.
3. Modify docker-compose.yml.
4. Attempt to run `hyper compose up` again.

Versions:
- `hyper -v`: `Hyper version 1.10.4, build 6fe5465`
- `uname -a`: `Linux felix-probook 4.8.4-1-ARCH #1 SMP PREEMPT Sat Oct 22 18:26:57 CEST 2016 x86_64 GNU/Linux`
- Hyper cloud: `tcp://us-west-1.hyper.sh:443`

**Comment by passcod** [comment]
I suppose this is the offending line? https://github.com/hyperhq/hypercli/blob/28bda292be7929beae13d1b4667191fd6f55fa0a/api/client/compose.go#L137 The command _always_ attempts to create a project, instead of checking whether it already exists.

**Comment by passcod** [comment]
Then I did a `hyper compose rm` to try to start over, forgetting I had to `compose kill` first. Instead of erroring, or of killing the services before removing, it succeeded:

```
Project [quotes]: Project deleted
```

But when I tried to bring it back up:

```
$ hyper compose up
Project [quotes]: Starting project
[0/2] [db]: Starting
[0/2] [web]: Starting
The dotted field 'sh.hyper.compose.oneoff' in 'base.config.labels.sh.hyper.compose.oneoff' is not valid for storage.
```

I have no idea what that means.

Further, the containers seem to still exist (when looked at with `hyper ps`) and are still up.

It seems like the `compose` subcommand is completely broken in various ways :(

**Comment by carmark** [comment]
@passcod 

`hyper compose` is a little different from `docker-compose`, since `docker-compose` only operate the docker container via docker API, but `hyper compose` has it's own compose API. 

It will save the compose project if you `up` or `create` a compose project, and you can not do it again if the previous operation was successful, since the duplicate project name checking will fail.  The only way to update the compose project is `down` your compose project and `up'/`create` it again.

Thanks,

**Comment by passcod** [comment]
You might want to change the docs, then, because it doesn't say that.

**Comment by suda** [comment]
@carmark `down` and `up` sequence does work but it creates new volumes leaving previous one dangling. Is there a way to update the project and reuse the volumes?
