### ISSUE TITLE
Create volume from Local Directory does not work on Windows

### ISSUE THREAD

**Issue by chosenken** [hyperhq/hypercli#193]
Hello.  When I attempt to start a container, and have it load data from a local volume on Windows 10, the CLI returns with the following error (I give the command as well):

```
G:\Games\Minecraft-Technic\server>hyper run -d -p 25565:25565 -e EULA=TRUE -e VERSION=1.7.10 -e TYPE=FORGE -e FORGEVERSION=10.13.4.1614 -e ALLOW_NETHER=true -e ENABLE_COMMAND_BLOCK=true -e OPS=chosenken --size=m2 -v G:\Games\Minecraft-Technic\server\:/data --name minecraft_server itzg/minecraft-server
hyper: Error response from daemon: Invalid bind mount spec "G:\\Games\\Minecraft-Technic\\server\\:/data": volumeinvalidmode: invalid mode: "/data".
```
It looks like in the function [ParseVolumesFrom](https://github.com/hyperhq/hypercli/blob/33567c0f665099131402420be38a1497aca222dc/volume/volume.go#L97) that it splits on `:`, which will be passed in from Windows.

For now I'll try on uploading a zip some where.  I also tried running this from MINGW64 and had the same error.

**Comment by carmark** [comment]
@chosenken The download link of `hypercli` on Windows is not latest, you have to compile it by yourself with this repo if you want to use it on Windows.

**Comment by chosenken** [comment]
After a bit of digging, I was able to get the code from `master` to build.  I didn't actually update the vendered library, but instead made a [hack](https://gist.github.com/chosenken/96e99531ba665c6228e3db1cac08583a) to get it to work.  I do still get the same error message though.  Version information for it is below:

```bash
Client:
 Version:      1.10.6
 API version:  1.23
 Go version:   go1.7.5
 Git commit:   33567c0f6
 Built:        Wed, Feb  1, 2017  5:24:10 AM
 OS/Arch:      windows/amd64

Server:
 Version:      Hyper.sh Public Service
 API version:  1.23
 Go version:   go1.7.3
 Git commit:
 Built:
 OS/Arch:      linux/amd64
```

**Comment by carmark** [comment]
Thanks for your investigation, I will look deeper, and keep u posted.

**Comment by carmark** [comment]
@chosenken  After double check, this function of `ParseVolumesFrom` does not work on windows, you have to use it on Linux or MacOS.
