### ISSUE TITLE
Ubuntu 17.10 Artful

### ISSUE THREAD

**Issue by enigma0x7** [hyperhq/hypercli#244]
I was not sure where to submit this,

> 
> curl -sSL https://hypercontainer.io/install | bash
> 
> Welcome to Install HyperContainer...
> 
> Hint: Hyper installer need root privilege
> 
> [ERROR] : Hyper support ubuntu( trusty utopic vivid wily xenial ), but current is artful(17.10)
> 

I am trying to get hypercontainer working on Ubuntu Budgie Desktop, is there is a specific reason Artful is not compatible?

**Comment by carmark** [comment]
Please open another issue on https://github.com/hyperhq/hyperd
