### ISSUE TITLE
Region support broken in the Hypercli Docker image

### ISSUE THREAD

**Issue by mirosval** [hyperhq/hypercli#251]
When running Hyper CLI via Docker I get:

```bash
docker run -it --privileged -v /var/run/docker.sock:/var/run/docker.sock -e HYPER_ACCESS=$HYPER_ACCESS -e HYPER_SECRET=$HYPER_SECRET hyperhq/hypercli hyper --region=eu-central-1 ps
flag provided but not defined: --region
See 'hyper --help'.
```

Also the ENV variable doesn't seem to do anything:
```bash
docker run -it --privileged -v /var/run/docker.sock:/var/run/docker.sock -e HYPER_ACCESS=$HYPER_ACCESS -e HYPER_SECRET=$HYPER_SECRET -e HYPER_DEFAULT_REGION=eu-central-1 hyperhq/hypercli hyper ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES               PUBLIC IP
Found a newer version, downloading...
```

There should have been 3 containers in Frankfurt, I have 0 containers in US.

it works fine on OSX.

**Comment by bergwolf** [comment]
Thanks for reporting! The hyperhq/hypercli image needs to be updated.

**Comment by mirosval** [comment]
I love hyper.sh! I forgot to mention that the `hyper` executable inside the image is correct & recent, because if I manually log in to the container with `docker run -it ..... hyperhq/hypercli bash` and then run `hyper` it works as advertised. It only does not work when I pass the arguments directly in the docker invocation.

**Comment by bergwolf** [comment]
That's because the `hyper` command will download the latest version automatically.

See the `Found a newer version, downloading...` message in your original comment.

**Comment by bergwolf** [comment]
updated docker hub `hyperhq/hypercli:latest` image.
