### ISSUE TITLE
"Environment is invalid" if env vars contain newlines

### ISSUE THREAD

**Issue by themightychris** [hyperhq/hypercli#260]
There's a discussion about this on the forum from last October: https://forum.hyper.sh/t/error-with-environment-variables-with-multiline-values/698

If you try to pass a multiline config like this:

```bash
HAB_NGINX="$(cat config.toml)" hyper run -d --name my-frontend -p 80:80 -e HAB_NGINX jarvus/nginx
```

you get:
```
hyper: Error response from daemon: Environment is invalid, should be [A-Za-z_][A-Za-z0-9_]*.
```

It works fine if you replace `hyper` with `docker`

**Comment by thatsheel** [comment]
Possibly hijacking, but this also prevents you from executing the following command to set up elastic search:

`hyper run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.3.0`

As per https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

**Comment by themightychris** [comment]
@thatsheel that's related, looks like there's a broader discussion on what can be allowed in env variable names: https://stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names

But while there's debate on what should be allowed in env var names, their values should definitely not be subjected to the same regex and can contain anything

**Comment by Jimmy-Xu** [comment]
This issue had been fixed.

```
$ V="$(cat /tmp/test.env)"

$ echo $V
TEST_AAA=aaa
discovery.type=single-node

$ hyper run -it -e "$V" busybox env
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=5ad2e4786b27
TEST_AAA=aaa
discovery.type=single-node
```

**Comment by themightychris** [comment]
Thanks @Jimmy-Xu !

It doesn't look like new releases get made in this GitHub repository anymore, how can I obtain a release that I know will include this fix?

**Comment by homerjam** [comment]
Any chance of getting a version bump and a release (github/homebrew) with this fix?

**Comment by Jimmy-Xu** [comment]
It's a server side issue, there is no need to update cli.
