### ISSUE TITLE
[bug] Specify host name like `foo.bar.baz` cause timeout when running a container

### ISSUE THREAD

**Issue by Crazykev** [hyperhq/hypercli#29]
**How to reproduce:**
```
hyper run -h foo.bar.baz busybox hostname
```
Got error `timeout to wait container state`

**Comment by carmark** [comment]
verified and fixed

[lei@h8s-single hypercli]$ ./hyper/hyper run -h foo.bar.baz busybox hostname
foo.bar.baz
[lei@h8s-single hypercli]$
