### ISSUE TITLE
run  -d  busybox false gets wrong exited code and error

### ISSUE THREAD

**Issue by xlgao-zju** [hyperhq/hypercli#37]
**How to Reproduce:**
```
hyper run  -d  busybox false
```

**Comment by carmark** [comment]
this is an issue while calling `wait` API to get exit status

**Comment by xlgao-zju** [comment]
So, it is hard to fix this issue. Or, we will not fix it for a long time?

**Comment by carmark** [comment]
`run` a container with option `-d` will not get exit code, you can try same command with docker command.  However, there is another issue while running a container without tty.  I fixed that issue on test environment, you can try it.

**Comment by xlgao-zju** [comment]
fixed. close it.
