### ISSUE TITLE
[bug] `run -e=KEY` in hyper is not consist with docker

### ISSUE THREAD

**Issue by Crazykev** [hyperhq/hypercli#75]
`docker run -e FOO busybox env`
Get result:
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=2da5648c6781
HOME=/root

`hyper run -e FOO busybox env`
Get result:
> hyper: Error response from daemon: Misconfigured environment FOO, Env name should match [A-Za-z_][A-Za-z0-9_]*.

enviroment FOO is not configured on local host.

**Expect:**
behavior should be consist with docker **Or** use a more inspiring error message. 

https://github.com/hyperhq/hypercli/blob/integration-test/integration-cli/todo/cli/docker_cli_run_test.go#L772-L879

**Comment by gao-feng** [comment]
https://github.com/hyperhq/hyperd/pull/322
