### ISSUE TITLE
[bug] create container with nonexistent image 

### ISSUE THREAD

**Issue by YaoZengzeng** [hyperhq/hypercli#89]
I create a container by nonexistent image such as "test234".As usual it should return the error message "No such image: test456:latest",but in hyper, it will response "No such image: test456",without tag "latest".

**Comment by Jimmy-Xu** [comment]
$ docker create test456
```
Unable to find image 'test456:latest' locally
Pulling repository docker.io/library/test456
Error: image library/test456 not found
```

$ hyper create test456    
```
Unable to find image 'test456:latest' locally
Pulling repository docker.io/library/test456
Error: image library/test456 not found
```

**Comment by Jimmy-Xu** [comment]
**imaged api**

$ curl -s -H "Content-Type: application/json" -XPOST -H "Authorization: Tenant=53f69a814697465b9716b38ab5863891 Credential=access_key/credential-scope" http://127.0.0.1:23456/containers/create?name=mybusybox -d '{"Image":"test456","Volumes":{"/tmp":{}}}'
```
No such image: test456:latest
```

----------------------------------

**apirouter api**

$ curl -k \   
  -H "Content-Type: application/json" \
  -H "X-Hyper-Date: 20160523T111523Z" \
  -H "X-Hyper-Content-Sha256: da5d60143325e3250a74d433eb97d73d8442f268cb80854d33f3eb8539aac2e7" \
  -H "Host: 147.75.195.39:6443" \
  -H "Authorization: HYPER-HMAC-SHA256 Credential=BVYLVWWAKRB6H3GL9425OG4K/20160523/us-west-1/hyper/hyper_request, SignedHeaders=content-type;host;x-hyper-content-sha256;x-hyper-date, Signature=9b59ed6e209879ef0ed525e6c9f3ebbf3a99d6677681091c7837fe3f0aff3cdd" \
  -X POST \
  -d '{"Image":"test456","Volumes":{"/tmp":{}}}
' \
  https://147.75.195.39:6443/v1.23/containers/create\?name\=test
```
Error: No such image: test456
```
